// Lesson 6 "Taste the World" — 유인물 3장(2026-10-05)에서 옮김
// 영영풀이·예문: 인쇄된 글자 / 한글 뜻: '뜻' 칸의 아이 손글씨(선생님이 불러 준 뜻)
// 형식: [번호, 단어, 품사, 영영풀이, 예문, 예문 속 정답 형태, 빈칸에 같이 들어갈 수 있는 단어들]
export default {
  id: 'L06',
  order: 6,
  title: 'Taste the World',
  rows: [
    [1, 'add', 'verb', 'to put something with something else to increase, complete, or improve it', 'You can add some salt to the soup.', 'add', []],
    [2, 'bowl', 'noun', 'a round container with an open top for holding food', 'Mix the vegetables in a big bowl.', 'bowl', ['pot', 'dish']],
    [3, 'clothing', 'noun', 'the things that people wear', 'We bought some new clothing.', 'clothing', []],
    [4, 'colorful', 'adj', 'having a lot of different colors', 'Do you like colorful clothes?', 'colorful', ['traditional', 'Hawaiian', 'Thai', 'popular', 'famous', 'fresh']],
    [5, 'culture', 'noun', 'the beliefs, way of life, art, and customs that are shared and accepted by people in a particular society', 'We learned about Korean culture.', 'culture', ['weather']],
    [6, 'dip', 'verb', 'to put something into a liquid and take it out quickly', 'She dips French fries in ketchup.', 'dips', []],
    [7, 'dish', 'noun', 'a type of food that is cooked in a particular way and served as part of a meal; a flat container with low sides, for serving food from or cooking food in', 'Bulgogi is a famous Korean dish.', 'dish', []],
    [8, 'enjoy', 'verb', 'to get pleasure from something', 'I enjoyed playing the violin.', 'enjoyed', []],
    [9, 'famous', 'adj', 'known by very many people', 'The Mona Lisa is a famous painting.', 'famous', ['popular', 'traditional', 'colorful']],
    [10, 'fresh', 'adj', 'newly made or produced', 'Those vegetables look fresh.', 'fresh', ['colorful', 'tasty', 'sour', 'popular']],
    [11, 'Hawaiian', 'adj', 'belonging or relating to the US state of Hawaii, its people, or language', "I'd like to try on a traditional Hawaiian dress.", 'Hawaiian', ['Thai', 'colorful', 'famous', 'popular']],
    [12, 'heat', 'verb', 'to make hot or warm', 'Can you heat the soup?', 'heat', ['taste', 'smell', 'add', 'pick up']],
    [13, 'island', 'noun', 'an area of land surrounded by water', 'Jeju-do is a big island.', 'island', []],
    [14, 'look', 'verb', 'to seem; to turn your eyes towards something, so that you can see it', 'The dog looks happy.', 'looks', ['sound']],
    [15, 'mean', 'verb', 'to have or represent a particular meaning', 'The red light means "to stop."', 'means', []],
    [16, 'pick up', 'phrase', 'to lift something or someone up', 'Could you pick up the pencil?', 'pick up', []],
    [17, 'popular', 'adj', 'liked by many people', 'Frozen is a popular movie.', 'popular', ['famous', 'colorful', 'traditional']],
    [18, 'pot', 'noun', 'a deep and round container used for cooking', 'My grandmother has an old pot.', 'pot', ['bowl', 'dish']],
    [19, 'salad', 'noun', 'vegetables mixed together for eating', 'She put some tomatoes in her salad.', 'salad', ['bowl', 'pot', 'dish']],
    [20, 'shrimp', 'noun', 'a small sea creature that you can eat, which has ten legs and a soft shell', 'I bought fresh shrimp in the market.', 'shrimp', ['salad']],
    [21, 'smell', 'verb', 'to notice or recognize a particular smell', 'The towel smells nice.', 'smells', ['look']],
    [22, 'sound', 'verb', 'to seem in a certain way, like when something seems good, bad strange, etc.; something that you can hear', 'The music sounds great.', 'sounds', []],
    [23, 'sour', 'adj', 'having a taste like that of a lemon', 'This candy is too sour for me.', 'sour', ['colorful']],
    [24, 'taste', 'verb', 'to have a particular taste', 'Ice cream tastes sweet.', 'tastes', ['smell', 'look']],
    [25, 'tasty', 'adj', 'pleasing to taste', "Josh's sandwiches were very tasty.", 'tasty', ['fresh', 'popular', 'famous', 'sour', 'colorful', 'traditional']],
    [26, 'Thai', 'adj', 'belonging or relating to Thailand, its people, or language', 'Amy has some Thai friends.', 'Thai', ['Hawaiian', 'famous', 'popular']],
    [27, 'traditional', 'adj', 'being part of the beliefs, customs or way of life of a particular group of people, that have not changed for a long time', 'She wore a traditional dress.', 'traditional', ['Hawaiian', 'Thai', 'colorful', 'famous', 'popular']],
    [28, 'weather', 'noun', 'the temperature and other conditions such as sun, rain, and wind', 'The weather is cold in Alaska.', 'weather', []],
  ],
  // [보여줄 뜻, 함께 인정할 답, 부모 확인 메모]
  korean: {
    add: [['추가하다', '첨가하다'], ['더하다', '넣다']],
    bowl: [['그릇'], ['사발', '공기']],
    clothing: [['옷', '의복'], ['의류']],
    colorful: [['색색의'], ['다채로운', '화려한', '알록달록한', '형형색색의']],
    culture: [['문화'], []],
    dip: [['살짝 담그다'], ['담그다', '찍다', '적시다']],
    dish: [['요리', '그릇'], ['음식', '접시']],
    enjoy: [['즐기다'], ['즐거워하다']],
    famous: [['유명한'], ['유명하다']],
    fresh: [['신선한'], ['신선하다', '싱싱한']],
    Hawaiian: [['하와이의', '하와이 사람(의)'], ['하와이인의', '하와이어', '하와이인'], '아이 필기가 겹쳐 있어 "하와이의, 하와이 사람"으로 읽음'],
    heat: [['데우다'], ['가열하다', '뜨겁게 하다']],
    island: [['섬'], []],
    look: [['~해 보이다', '보다'], ['보이다', '바라보다', '쳐다보다'], '아이 필기 일부가 흐림 — "~해 보이다, 보다"로 읽음'],
    mean: [['의미하다'], ['뜻하다']],
    'pick up': [['줍다'], ['집어 들다', '들어 올리다', '집다']],
    popular: [['인기 있는'], ['인기있는', '인기 많은', '대중적인']],
    pot: [['냄비', '솥'], ['단지']],
    salad: [['샐러드'], []],
    shrimp: [['새우'], []],
    smell: [['냄새가 나다'], ['냄새 맡다', '냄새를 맡다', '냄새']],
    sound: [['~하게 들리다', '소리'], ['들리다', '~처럼 들리다']],
    sour: [['(맛이) 신', '시큼한'], ['시다', '신맛의', '신맛이 나는'], '아이 필기는 "신 맛의"로 보임'],
    taste: [['맛이 나다'], ['맛보다', '맛', '~한 맛이 나다']],
    tasty: [['맛있는'], ['맛있다', '맛 좋은']],
    Thai: [['태국의', '태국인(의)'], ['태국어', '태국 사람', '태국인']],
    traditional: [['전통적인'], ['전통의', '전통적']],
    weather: [['날씨'], ['기상']],
  },
  // 풀이가 비슷하거나 서로의 풀이에 들어 있는 단어 — 객관식 보기에 같이 나오지 않게
  confusable: [
    ['taste', 'tasty'],
    ['taste', 'smell'],
    ['taste', 'mean'], // 정답을 가린 풀이가 모두 "a particular ____" 라서 서로 헷갈림
    ['smell', 'mean'],
    ['look', 'sound'],
    ['bowl', 'pot'],
    ['bowl', 'dish'],
    ['pot', 'dish'],
    ['Hawaiian', 'Thai'],
    ['famous', 'popular'],
    ['culture', 'traditional'],
    ['tasty', 'L05:delicious'], // Lesson 5 delicious(very pleasant to taste)와 풀이가 거의 같음
  ],
  // 사진 판독 메모: 필기에 가려 있던 인쇄 글자
  notes: {
    11: "예문 앞부분(I'd like)이 필기에 가려 있었음",
    13: '단어 칸 "island" 위에 필기가 겹쳐 있었음',
  },
};
